version: "3"
services:
  mysqldb:
    image: mysql:8
    expose:
      - 3306
    ports:
      - 3306:3306
    networks:
      - notanothertodo-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=notanothertodo

networks:
  notanothertodo-mysql: